spring.application.name=battleforge-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/battleforge
spring.datasource.username=postgres
spring.datasource.password=123123123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect