apiVersion: v1
kind: ConfigMap
metadata:
 name: backend-configmap
data:
 SERVER_PORT: "8080"
 DB_NAME: battleforge
 DB_HOST: battleforge-db-0.battleforge-db-headless
 DB_PORT: "5432"
 JPA_DDL_AUTO: update
 JPA_SHOW_SQL: "true"

 